// Generated by Wrangler by running `wrangler types`
import type { Request as WorkerRequest, ExecutionContext, D1Database } from "@cloudflare/workers-types/experimental"
interface Env {
	DB: D1Database;
}
