// Generated by Wrangler by running `wrangler types`
// This file should be placed in the src directory of your Pages project or Svelte will not pick it up.
import type { Request as WorkerRequest, ExecutionContext, D1Database } from "@cloudflare/workers-types/experimental"
interface Env {
	DB: D1Database;
}
